sudo: false

language: php

env:
  global:
    - COMPOSER_ROOT_VERSION=4.0.x-dev

matrix:
  fast_finish: true
  include:
    - php: 5.6
      env: DB=MYSQL PHPUNIT_TEST=1
    - php: 7.0
      env: DB=MYSQL PHPUNIT_TEST=1
    - php: 7.1
      env: DB=MYSQL PDO=1

before_script:
  - phpenv rehash
  - phpenv config-rm xdebug.ini
  - composer validate
  - composer require --no-update silverstripe/recipe-cms:1.0.x-dev
  - composer install --prefer-dist

script:
  - if [[ $PHPUNIT_TEST ]]; then vendor/bin/phpunit; fi
